# Generated by Django 5.1.4 on 2024-12-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateField()),
                ('action', models.CharField(choices=[('login', 'Login Successfully'), ('question', 'Look question list'), ('vote', 'Vote a question'), ('detail', 'View single question info')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polluser')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='publication date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polluser')),
            ],
        ),
    ]
