# Generated by Django 5.1.4 on 2024-12-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_userlog_userquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestion',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
