# Generated by Django 5.1.4 on 2024-12-16 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_pub_date_alter_userquestion_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 16, 12, 40, 38, 630264, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 12, 16, 12, 40, 38, 631346, tzinfo=datetime.timezone.utc)),
        ),
    ]
