# Generated by Django 5.1.4 on 2024-12-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_pub_date_alter_userquestion_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
    ]
