# Generated by Django 5.1.4 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_author_delete_userquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login Successfully'), ('question', 'Look question list'), ('vote', 'Vote a question'), ('detail', 'View single question info'), ('choice+', 'Adding a choice to a question'), ('question+', 'Adding a new question')], max_length=20),
        ),
    ]
